version: 2.1

executors:
  python-docker:
    docker:
      - image: cimg/python:3.10

jobs:
  test_service:
    executor: python-docker
    steps:
      - checkout
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest tests/

  build_and_deploy_bento:
    executor: python-docker
    steps:
      - checkout
      - setup_remote_docker
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: bentoml build
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            bentoml containerize llm_service:latest -t $DOCKER_USERNAME/llm_service:latest
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKER_USERNAME/llm_service:latest

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test_service
      - build_and_deploy_bento:
          requires:
            - test_service